# -*- coding: utf-8 -*-
"""osaweb.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-LXCeNCFcqy8ANsJNS-V2qYki439fCbb
"""

from IPython.display import HTML
url = 'https://osandal.github.io/'
iframe = '<iframe src=' + url + ' width="100%" height=800></iframe>'
HTML(iframe)